com.honey.google.client.id=609985158917-cv8r77jfiqs9p5fejnmpprq6ktn8vr7c.apps.googleusercontent.com

com.honey.google.client.secret=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



com.honey.kakao.client.id=926c20ad6655d0951df3feb3788f0d99

com.honey.kakao.client.secret=xWuBwDKdzO6WVAXKhgWzrnJS0yEw4E7w